client/templates/games/game.js, client/templates/games/index.js, client/templates/games/show.html, client/templates/games/show.js, lib/collections/games.js, lib/models/game.js, lib/utility.js
Resolves #20 and everything still works
=> Creates Game model layer with instance methods instead of random functions

client/lib/wgo/wgo.js, client/templates/games/game.js, client/templates/games/show.html, lib/collections/games.js, lib/models/game.js, lib/utility.js
Fixed issue #22 and everything still works.
=> Completed new board update method

lib/models/game.js
Puts new games on the top of the feed (before it was at the bottom)
=> Added lastActivityAt when game gets created

client/templates/match/board/board.html, client/templates/match/board/board.js
=> Destroy board when exiting Match page

client/stylesheets/style.scss, client/templates/lobby/createGame.html, client/templates/match/board/board.js, client/templates/match/playerBox/historyButtons.html, client/templates/match/playerBox/historyButtons.js, client/templates/match/playerBox/playerBox.html, client/templates/match/playerBox/playerBox.js
=> Implemented move history for Completed games

client/stylesheets/style.scss, client/templates/accountMenu/accountMenu.html, client/templates/accountMenu/accountMenu.js, client/templates/accountMenu/history/history.html, client/templates/accountMenu/history/history.js, client/templates/accountMenu/userProfile/userProfile.html, client/templates/accountMenu/userProfile/userProfile.js, client/templates/accountMenu/userProfile/userProfileField.html, client/templates/accountMenu/userProfile/userProfileField.js, lib/collections/users.js, lib/router.js, server/accounts.js
=> Implemented userprofile

client/stylesheets/style.scss, client/templates/match/playerBox/playerBox.html, client/templates/match/playerBox/playerBox.js, lib/models/game.js, lib/utility.js
=> Implemented resign functionality

client/lib/jquery-confirm/css/jquery-confirm.css, client/lib/jquery-confirm/js/jquery-confirm.js, client/templates/match/playerBox/playerBox.js, lib/models/game.js
Adds resignation confirmation to #40
=> Added jQuery confirmation for resign button

.meteor/packages, .meteor/versions, client/lib/subscriptions.js, client/templates/lobby/userItem.html, client/templates/lobby/userItem.js, client/templates/match/playerBox/playerBox.html, client/templates/match/playerBox/playerBox.js, server/publications.js
Applied to both lobby and match pages. Resolves #19.
=> Only show user icon if that user is online

client/stylesheets/style.scss, client/templates/accountMenu/accountMenu.html, client/templates/accountMenu/accountMenu.js, client/templates/accountMenu/history/history.html, client/templates/accountMenu/history/history.js, client/templates/accountMenu/userProfile/editUserProfile.html, client/templates/accountMenu/userProfile/editUserProfile.js, client/templates/accountMenu/userProfile/userProfile.html, client/templates/accountMenu/userProfile/userProfile.js, client/templates/accountMenu/userProfile/userProfileField.html, client/templates/accountMenu/userProfile/userProfileField.js, client/templates/lobby/gameTable.html, lib/router.js
=> Implemented basic user profile and links to edit profile

client/templates/accountMenu/userProfile/editUserProfile.js, client/templates/accountMenu/userProfile/userProfile.js
Fixes bug in pull request #38. Also redirects user to userprofile after editing profile.
=> Fixed bug and redirects

client/templates/includes.html, lib/router.js
Resolves issue #45. Fixed with better routing
=> Route fixing

lib/router.js
Router now properly 404s on undefined users
=> Route Fix & Reordering

.meteor/packages, .meteor/versions, client/stylesheets/style.scss, lib/router.js
Added progress bar at top. Resolved #32
=> Added progress bar for loading Lobby and Match

client/stylesheets/style.scss, client/templates/match/history/historyButtons.html, client/templates/match/history/historyButtons.js, client/templates/match/history/messageHistoryButtons.js, lib/router.js
Just click on the current move number and a little popup shows. Resolves #51.
=> Allows user to go to typed move number in replay

lib/models/game.js
Fixes bug introduced by changing library from underscore to lodash in #14
=> Fixed score function when both players accept MarkDead mode

lib/models/game.js
Make message replay in #14 include the final 'Game Ended' message when MarkDead mode is enabled.
=> Added 'game ended' message to replay in case of MarkDead

client/templates/accountMenu/userProfile/userProfile.js
Was incorrectly only displaying games that the current user has with the observed player's
=> Fixed game filtering bug

.meteor/packages, .meteor/versions, client/stylesheets/style.scss, client/templates/lobby/createGame.html, client/templates/lobby/createGame.js, client/templates/match/playerBox/gameTimer.html, client/templates/match/playerBox/gameTimer.js, client/templates/match/playerBox/playerBox.html, lib/collections/games.js, lib/methods/games.js, lib/models/game.js
Implemented basic chess-style time controls with no increment or any other fancy stuff. You can choose whether a game is timed or not in the Create Game menu. Resolves #17.
Next, we have to do things around the timer. For example:
* Display whether a new game is timed or not so other people can choose whether to join
* Filter all your timed games (since they're more urgent)
* etc.
=> Implemented basic time controls (time bank only)

client/lib/subscriptions.js, client/stylesheets/style.scss, client/templates/globalChat/activeUser.html, client/templates/globalChat/activeUser.js, client/templates/globalChat/globalChat.html, client/templates/globalChat/globalChat.js, client/templates/globalChat/onlineUsers.html, client/templates/globalChat/onlineUsers.js, client/templates/lobby/createGame.js, client/templates/lobby/lobby.html, client/templates/lobby/lobby.js, lib/collections/chatrooms.js, server/publications.js
- Bootstrap styled global chat & online friends
- Global chat autoscroll
- Last 100 messages shown
=> Global chat implemented

client/stylesheets/style.scss, client/templates/layout.html, client/templates/lobby/createGame.html, client/templates/lobby/createGame.js, client/templates/lobby/gameRow.html, client/templates/lobby/gameRow.js, client/templates/match/messages/messageContainer.html, client/templates/match/messages/messageContainer.js, client/templates/match/playerBox/gameTimer.js, client/templates/yourGames/yourGameRow.html, client/templates/yourGames/yourGameRow.js, client/templates/yourGames/yourGamesTable.html, client/templates/yourGames/yourGamesTable.js, lib/utility.js
* Displays whether a game is timed or not in basic table + Your Games
* Filters all your timed games (since they're more urgent)
* Allows you to click on "minutes" to change it to "hours" in the New Game dialog
* Clicking on "Enable Time" label sets it correctly
Resolves #75.
=> Implemented extra functionality around time controls

client/stylesheets/style.scss, client/templates/accountMenu/userProfile/filtering/filtering.html, client/templates/accountMenu/userProfile/filtering/filtering.js, client/templates/accountMenu/userProfile/gameHistory/gameHistory.html, client/templates/accountMenu/userProfile/userProfile.html, client/templates/accountMenu/userProfile/userProfile.js
- Outcome filter
- Username filter
- Open or archived game filter
=> Enhanced filters on profile page

client/templates/globalChat/onlineUsers.js
=> Changed online users calculation

client/stylesheets/style.scss, client/templates/accountMenu/userProfile/userProfile.html, client/templates/accountMenu/userProfile/userStats/userStats.html, client/templates/accountMenu/userProfile/userStats/userStats.js, client/templates/lobby/gameRow.html, client/templates/yourGames/yourGameRow.html
Resolved #58  (except for Avatars...which I don't think are possible on public meteor servers)
- Added glyphicons to moves and board on the table rows.
- Added a basic statistic overview panel to the profile. It looks kind ugly though :(
=> Profile enhancements

client/templates/match/board/eventHandlers.js
=> Fixed hover piece showing when you take a piece

client/templates/accountMenu/userProfile/filtering/filtering.js, client/templates/accountMenu/userProfile/userProfile.js
Filters now reload from previous saved state
Also fixed .fetch() bug to not run on undefined cursor in userProfile.js
=> Filters now reload from previous saved state

client/stylesheets/style.scss, client/templates/lobby/createGame.html, client/templates/lobby/createGame.js, client/templates/lobby/gameRow.js, client/templates/match/board/board.js, client/templates/match/history/historyButtons.js, client/templates/match/playerBox/gameTimer.html, client/templates/match/playerBox/gameTimer.js, client/templates/yourGames/yourGameRow.js, lib/methods/games.js, lib/models/game.js, lib/utility.js
* Added byo-yomi time controls and all hookups
* Added marker in All Games table
* Made currently-ticking time bigger in Match view
* Show currently-ticking time in Your Games table
* Better experience creating Timed Games and selecting Main Time and/or Byo-yomi
Resolves #76.
=> Implemented byo-yomi time controls

client/stylesheets/style.scss
Scoped `.alert` styling to not apply anymore to notification request popup. Resolves #105.
=> Fixed issue with Match design when notifications request appears

client/templates/globalChat/globalChat.js
=> Prevent blank chat messages

client/helpers/config.js, client/stylesheets/style.scss, client/templates/lobby/userItem.js, client/templates/match/playerBox/playerBox.html, client/templates/match/playerBox/playerBox.js, lib/models/game.js, server/publications.js
Added some fields to Presences collection, including current route name and game ID (if applicable). Resolves #116. 
Possible follow-up: only start game when both users are present in the room.
=> Added in-game indicator that shows whether opponent's there

lib/models/game.js
finishes up https://github.com/yangez/go-meteor/pull/112
=> quickfix to not overwrite passCount

client/templates/challengeMenu/challengeMenu.js, lib/models/game.js
=> Fixed challenge edge case where sender doesn't acknowledge challenge

client/templates/match/history/historyButtons.js
* Left: back
* Right: forward
* Up: beginning
* Down: end
Resolves #124.
=> Added keyboard shortcuts to game history replay

lib/models/game.js
=> Fixed challenge bug when challenger is white

client/templates/lobby/lobby.js, client/templates/lobby/showGame.html, client/templates/match/history/historyButtons.js
* Removed non-archived requirement from lobby game
* Prevented lobby game from jumping to another one if it's already loaded
* Prevented up/down keys from scrolling when viewing game history
=> Small improvements to lobby and history

client/lib/responsive-bootstrap-toolkit/responsive-bootstrap-toolkit.js, client/stylesheets/style.scss, client/templates/helpers/board/board.js, client/templates/match/match.html
=> Made board responsive wherever it appears

client/stylesheets/style.scss, client/templates/menu/createGameMenu/createGame.html, lib/models/game.js
Fixed problem with absolute time controls dating all the way back to #97. Resolves #136.
=> Fixed absolute timer snapping back to previous time after expiring

client/stylesheets/lib/utility.scss, client/templates/menu/createGameMenu/createGame.html, client/templates/menu/createGameMenu/createGame.js
=> Created loading indicator for 'Create Game'

client/templates/lobby/globalChat/globalChat.html, client/templates/lobby/globalChat/globalChat.js, client/templates/menu/navMenu.html, client/templates/menu/privateMessages/privateMessages.html, client/templates/menu/privateMessages/privateMessages.js, client/templates/menu/privateMessages/receivedMessagesRow.html, client/templates/menu/privateMessages/receivedMessagesRow.js, lib/methods/rooms.js
=> Private messages implemented

client/stylesheets/match.scss, client/templates/helpers/board/board.js, client/templates/match/playerBox/actionButtons.html, client/templates/match/playerBox/actionButtons.js, client/templates/match/playerBox/playerBox.html, client/templates/match/playerBox/playerBox.js, lib/collections/games.js, lib/methods/games.js, lib/models/game.js
Players can now request a takeback and, if their opponent agrees, their previous move is erased. Some details:
* Timer is not rolled back
* 'last move' marker is not present
Resolves #103.
=> Implemented in-game takebacks

client/stylesheets/match.scss, client/templates/match/playerBox/playerBox.js
=> Linked in-game profile box to person's profile

client/stylesheets/match.scss, client/templates/match/playerBox/actionButtons.html, client/templates/match/playerBox/actionButtons.js, lib/methods/challenges.js, lib/methods/games.js, lib/models/challenge.js, lib/models/game.js
Rematches are just challenges with a special tag on them. When created from a rematch, games have a "rematchOf" tag on them so we can later determine which games were rematches, and possibly chain them together.
Resolves #101.
=> Implemented rematch functionality after game ends

client/templates/menu/yourGamesMenu/yourGamesMenu.js
=> Removed current game from 'Your Games' notification count

.meteor/packages, .meteor/versions, client/templates/lobby/globalChat/globalChat.html, client/templates/lobby/globalChat/globalChat.js, client/templates/lobby/globalChat/globalChatAutoComplete.html, client/templates/lobby/globalChat/onlineUsers.js
Uses the mizzao:autocomplete package.
Will have a separate PR for actual @ mention notifications.
=> Autocompletion for @username in global chat

client/templates/match/playerBox/actionButtons.js
=> Disabled cancel button unless you're part of the game

lib/models/game.js
=> Added byoyomi time settings to rematch

.meteor/packages, .meteor/versions, client/stylesheets/menu.scss, client/templates/helpers/board/board.js, client/templates/menu/navMenu.html, client/templates/menu/notificationsMenu/notificationItem.html, client/templates/menu/notificationsMenu/notificationItem.js, client/templates/menu/notificationsMenu/notificationsMenu.html, client/templates/menu/notificationsMenu/notificationsMenu.js, client/templates/menu/notificationsMenu/types/yourTurnItem.html, client/templates/menu/notificationsMenu/types/yourTurnItem.js, client/templates/menu/yourGamesMenu/yourGamesMenu.html, lib/collections/users.js, lib/methods/users.js, lib/models/game.js, lib/notifications.js
Added in-app notification menu and system for accessing it. The only notification implemented in this PR is the 'Your Turn' notification, which replaces the live counter next to the Your Games menu. Resolves #173.
Notes:
* Switched Menu item positioning to make more sense
* Implemented mark read + mark all read
* Viewing a game will mark all notifications related to that game as read
Next, will switch Challenges interface over to the Notifications architecture so it's consistent.
=> Implemented in-app notifications menu for 'your turn'

.meteor/packages, .meteor/versions, client/helpers/config.js, client/templates/match/match.js, client/templates/match/playerBox/actionButtons.js, lib/collections/users.js, lib/models/game.js, lib/notifications.js
Enabled web notifications for 'Your Move'.
Resolves #180.
=> Enabled desktop notifications on Herald

.meteor/packages, .meteor/versions, lib/collections/users.js, lib/notifications.js, lib/utility.js, server/accounts.js
Started using mizzao:meteor-user-status instead of Presences because it looks more reliable.
* Sends new challenge recipient an email if they're not online
* Sends accepted challenge email to sender if they're not online
Resolves #129.
=> Send email for challenge if user not online

client/templates/lobby/globalChat/globalChat.js, lib/collections/rooms.js, lib/collections/users.js, lib/methods/rooms.js, lib/methods/users.js
=> Fixes Private Messages

client/lib/models/board.js, client/templates/helpers/board/board.js, lib/collections/games.js, lib/collections/positions.js, lib/methods/games.js, lib/utility.js
Also made MarkDead less laggy by reducing db calls. Resolves #5.
=> Clicking MD stone sets entire block instead of single stone
